// TrustBank — theme presets (editor + mini-site)
// Each theme controls: background, text, accent, card surfaces, gradients,
// font pairing, video grid style, and CSS custom properties

export type VideoLayout = 1 | 2 | 3;

export interface Theme {
  id: string;
  label: string;
  emoji: string;
  category: 'dark' | 'light' | 'gradient' | 'luxury';
  description: string;
  // Raw CSS vars injected into the site root
  vars: {
    '--tb-bg': string;
    '--tb-bg2': string;
    '--tb-bg3': string;
    '--tb-text': string;
    '--tb-text2': string;
    '--tb-border': string;
    '--tb-radius': string;
    '--tb-font': string;
    '--tb-font-display': string;
    '--tb-shadow': string;
    '--tb-card-style': string; // 'glass' | 'solid' | 'outline' | 'flat'
    '--tb-link-style': string; // 'pill' | 'card' | 'line' | 'block'
  };
  // Tailwind gradient for the page background (used in SSR/static)
  bgGradient: string;
  // Avatar/card overlay effect
  avatarStyle: string; // 'ring-accent' | 'ring-white' | 'glow' | 'border-gradient' | 'shadow'
  // Preview thumbnail color
  previewBg: string;
  previewText: string;
}

export const THEMES: Theme[] = [
  // ── 1. MIDNIGHT ────────────────────────────────────────────────────────────
  {
    id: 'midnight',
    label: 'Midnight',
    emoji: '🌑',
    category: 'dark',
    description: 'Deep blue-black. Spotify energy.',
    bgGradient: 'from-slate-900 via-[#0d1117] to-slate-950',
    avatarStyle: 'ring-accent',
    previewBg: '#0d1117',
    previewText: '#e2e8f0',
    vars: {
      '--tb-bg':          '#0d1117',
      '--tb-bg2':         '#161b22',
      '--tb-bg3':         '#21262d',
      '--tb-text':        '#e6edf3',
      '--tb-text2':       '#8b949e',
      '--tb-border':      'rgba(240,246,252,0.1)',
      '--tb-radius':      '12px',
      '--tb-font':        '"Inter", system-ui, sans-serif',
      '--tb-font-display':'"Cal Sans", "Plus Jakarta Sans", sans-serif',
      '--tb-shadow':      '0 0 0 1px rgba(240,246,252,0.1), 0 16px 40px rgba(0,0,0,0.5)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  // ── 2. NOIR ─────────────────────────────────────────────────────────────────
  {
    id: 'noir',
    label: 'Noir',
    emoji: '⬛',
    category: 'dark',
    description: 'Pure black. Maximum contrast. Luxo absoluto.',
    bgGradient: 'from-black via-black to-zinc-950',
    avatarStyle: 'ring-white',
    previewBg: '#000000',
    previewText: '#ffffff',
    vars: {
      '--tb-bg':          '#000000',
      '--tb-bg2':         '#111111',
      '--tb-bg3':         '#1a1a1a',
      '--tb-text':        '#ffffff',
      '--tb-text2':       '#888888',
      '--tb-border':      'rgba(255,255,255,0.08)',
      '--tb-radius':      '8px',
      '--tb-font':        '"Helvetica Neue", "Arial", sans-serif',
      '--tb-font-display':'"Neue Haas Grotesk", "Helvetica Neue", sans-serif',
      '--tb-shadow':      '0 0 0 1px rgba(255,255,255,0.05)',
      '--tb-card-style':  'outline',
      '--tb-link-style':  'block',
    },
  },

  // ── 3. NEON TOKYO ──────────────────────────────────────────────────────────
  {
    id: 'neon',
    label: 'Neon Tokyo',
    emoji: '🌆',
    category: 'gradient',
    description: 'Synthwave. Lo-fi. Cyberpunk glow.',
    bgGradient: 'from-[#0a0015] via-[#150025] to-[#0a0015]',
    avatarStyle: 'glow',
    previewBg: '#0a0015',
    previewText: '#f9a8d4',
    vars: {
      '--tb-bg':          '#0a0015',
      '--tb-bg2':         '#150025',
      '--tb-bg3':         '#1f0035',
      '--tb-text':        '#fce7f3',
      '--tb-text2':       '#c084fc',
      '--tb-border':      'rgba(192,132,252,0.2)',
      '--tb-radius':      '16px',
      '--tb-font':        '"Space Grotesk", sans-serif',
      '--tb-font-display':'"Space Grotesk", sans-serif',
      '--tb-shadow':      '0 0 30px rgba(168,85,247,0.15), 0 0 0 1px rgba(192,132,252,0.15)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  // ── 4. IVORY ─────────────────────────────────────────────────────────────
  {
    id: 'ivory',
    label: 'Ivory',
    emoji: '🤍',
    category: 'light',
    description: 'Clean white. Apple meets Notion.',
    bgGradient: 'from-gray-50 via-white to-slate-50',
    avatarStyle: 'shadow',
    previewBg: '#ffffff',
    previewText: '#1a1a1a',
    vars: {
      '--tb-bg':          '#fafafa',
      '--tb-bg2':         '#ffffff',
      '--tb-bg3':         '#f4f4f5',
      '--tb-text':        '#18181b',
      '--tb-text2':       '#71717a',
      '--tb-border':      'rgba(0,0,0,0.08)',
      '--tb-radius':      '14px',
      '--tb-font':        '"DM Sans", system-ui, sans-serif',
      '--tb-font-display':'"DM Serif Display", Georgia, serif',
      '--tb-shadow':      '0 1px 3px rgba(0,0,0,0.08), 0 8px 24px rgba(0,0,0,0.05)',
      '--tb-card-style':  'solid',
      '--tb-link-style':  'pill',
    },
  },

  // ── 5. GOLD ──────────────────────────────────────────────────────────────
  {
    id: 'gold',
    label: 'Gold',
    emoji: '✨',
    category: 'luxury',
    description: 'Rolex. Louis Vuitton. Ouro puro.',
    bgGradient: 'from-[#0c0900] via-[#1a1100] to-[#0c0900]',
    avatarStyle: 'border-gradient',
    previewBg: '#0c0900',
    previewText: '#fde68a',
    vars: {
      '--tb-bg':          '#0c0900',
      '--tb-bg2':         '#1a1400',
      '--tb-bg3':         '#261e00',
      '--tb-text':        '#fef3c7',
      '--tb-text2':       '#d97706',
      '--tb-border':      'rgba(234,179,8,0.2)',
      '--tb-radius':      '6px',
      '--tb-font':        '"Cormorant Garamond", Georgia, serif',
      '--tb-font-display':'"Cormorant Garamond", Georgia, serif',
      '--tb-shadow':      '0 0 0 1px rgba(234,179,8,0.15), 0 8px 32px rgba(234,179,8,0.05)',
      '--tb-card-style':  'outline',
      '--tb-link-style':  'line',
    },
  },

  // ── 6. OCEAN ─────────────────────────────────────────────────────────────
  {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    category: 'dark',
    description: 'Deep sea. Azul infinito.',
    bgGradient: 'from-[#020c18] via-[#051e3e] to-[#020c18]',
    avatarStyle: 'glow',
    previewBg: '#020c18',
    previewText: '#bae6fd',
    vars: {
      '--tb-bg':          '#020c18',
      '--tb-bg2':         '#051e3e',
      '--tb-bg3':         '#082c5a',
      '--tb-text':        '#e0f2fe',
      '--tb-text2':       '#38bdf8',
      '--tb-border':      'rgba(56,189,248,0.15)',
      '--tb-radius':      '12px',
      '--tb-font':        '"IBM Plex Sans", system-ui, sans-serif',
      '--tb-font-display':'"IBM Plex Mono", monospace',
      '--tb-shadow':      '0 0 40px rgba(14,165,233,0.12), 0 0 0 1px rgba(56,189,248,0.1)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'card',
    },
  },

  // ── 7. ROSE ──────────────────────────────────────────────────────────────
  {
    id: 'rose',
    label: 'Rose',
    emoji: '🌹',
    category: 'gradient',
    description: 'Soft pink editorial. Vogue meets Instagram.',
    bgGradient: 'from-[#1a0010] via-[#2a0018] to-[#1a0010]',
    avatarStyle: 'ring-accent',
    previewBg: '#1a0010',
    previewText: '#fecdd3',
    vars: {
      '--tb-bg':          '#1a0010',
      '--tb-bg2':         '#2a001c',
      '--tb-bg3':         '#3d0028',
      '--tb-text':        '#ffe4e6',
      '--tb-text2':       '#fb7185',
      '--tb-border':      'rgba(251,113,133,0.2)',
      '--tb-radius':      '20px',
      '--tb-font':        '"Playfair Display", Georgia, serif',
      '--tb-font-display':'"Playfair Display", Georgia, serif',
      '--tb-shadow':      '0 0 30px rgba(244,63,94,0.12), 0 0 0 1px rgba(251,113,133,0.12)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  // ── 8. FOREST ────────────────────────────────────────────────────────────
  {
    id: 'forest',
    label: 'Forest',
    emoji: '🌿',
    category: 'dark',
    description: 'Terra. Orgânico. Sustentável.',
    bgGradient: 'from-[#0a1a0a] via-[#0f2614] to-[#0a1a0a]',
    avatarStyle: 'ring-accent',
    previewBg: '#0a1a0a',
    previewText: '#bbf7d0',
    vars: {
      '--tb-bg':          '#0a1a0a',
      '--tb-bg2':         '#0f2614',
      '--tb-bg3':         '#163a1c',
      '--tb-text':        '#dcfce7',
      '--tb-text2':       '#4ade80',
      '--tb-border':      'rgba(74,222,128,0.15)',
      '--tb-radius':      '12px',
      '--tb-font':        '"Nunito", system-ui, sans-serif',
      '--tb-font-display':'"Nunito", system-ui, sans-serif',
      '--tb-shadow':      '0 0 30px rgba(34,197,94,0.1), 0 0 0 1px rgba(74,222,128,0.1)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  // ── 9. EDITORIAL ─────────────────────────────────────────────────────────
  {
    id: 'editorial',
    label: 'Editorial',
    emoji: '📰',
    category: 'light',
    description: 'Medium. Substack. Texto como arte.',
    bgGradient: 'from-amber-50 via-white to-stone-50',
    avatarStyle: 'shadow',
    previewBg: '#fffbf5',
    previewText: '#1c1917',
    vars: {
      '--tb-bg':          '#fffbf5',
      '--tb-bg2':         '#ffffff',
      '--tb-bg3':         '#f5f0e8',
      '--tb-text':        '#1c1917',
      '--tb-text2':       '#78716c',
      '--tb-border':      'rgba(0,0,0,0.1)',
      '--tb-radius':      '4px',
      '--tb-font':        '"Lora", Georgia, serif',
      '--tb-font-display':'"Merriweather", Georgia, serif',
      '--tb-shadow':      '0 1px 2px rgba(0,0,0,0.06), 0 4px 12px rgba(0,0,0,0.04)',
      '--tb-card-style':  'flat',
      '--tb-link-style':  'line',
    },
  },

  // ── 10. AURORA ───────────────────────────────────────────────────────────
  {
    id: 'aurora',
    label: 'Aurora',
    emoji: '🌌',
    category: 'gradient',
    description: 'Northern lights. Gradiente vivo e dinâmico.',
    bgGradient: 'from-[#050218] via-[#0d1130] to-[#050218]',
    avatarStyle: 'border-gradient',
    previewBg: '#050218',
    previewText: '#c7d2fe',
    vars: {
      '--tb-bg':          '#050218',
      '--tb-bg2':         '#0d1130',
      '--tb-bg3':         '#141850',
      '--tb-text':        '#e0e7ff',
      '--tb-text2':       '#818cf8',
      '--tb-border':      'rgba(129,140,248,0.2)',
      '--tb-radius':      '16px',
      '--tb-font':        '"Outfit", system-ui, sans-serif',
      '--tb-font-display':'"Outfit", system-ui, sans-serif',
      '--tb-shadow':      '0 0 60px rgba(99,102,241,0.15), 0 0 0 1px rgba(129,140,248,0.12)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  {
    id: 'cyber_violet',
    label: 'Cyber Lilac',
    emoji: '⚡',
    category: 'dark',
    description: 'Neon violet grid. Futurist dark.',
    bgGradient: 'from-[#0a0518] via-[#12082a] to-[#0a0518]',
    avatarStyle: 'glow',
    previewBg: '#0a0518',
    previewText: '#e9d5ff',
    vars: {
      '--tb-bg':          '#0a0518',
      '--tb-bg2':         '#12082a',
      '--tb-bg3':         '#1a0c3a',
      '--tb-text':        '#f5e6ff',
      '--tb-text2':       '#c4b5fd',
      '--tb-border':      'rgba(167,139,250,0.35)',
      '--tb-radius':      '18px',
      '--tb-font':        '"Orbitron", "Space Grotesk", sans-serif',
      '--tb-font-display':'"Orbitron", sans-serif',
      '--tb-shadow':      '0 0 40px rgba(192,132,252,0.2), 0 0 0 1px rgba(167,139,250,0.25)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },
  {
    id: 'cyber_azure',
    label: 'Cyber Azure',
    emoji: '🧿',
    category: 'dark',
    description: 'Cyan neon. Deep ocean tech.',
    bgGradient: 'from-[#030a14] via-[#051a2e] to-[#030a14]',
    avatarStyle: 'glow',
    previewBg: '#030a14',
    previewText: '#a5f3fc',
    vars: {
      '--tb-bg':          '#030a14',
      '--tb-bg2':         '#051a2e',
      '--tb-bg3':         '#082440',
      '--tb-text':        '#e0f7ff',
      '--tb-text2':       '#67e8f9',
      '--tb-border':      'rgba(34,211,238,0.35)',
      '--tb-radius':      '16px',
      '--tb-font':        '"Orbitron", "IBM Plex Sans", sans-serif',
      '--tb-font-display':'"Orbitron", sans-serif',
      '--tb-shadow':      '0 0 45px rgba(6,182,212,0.18), 0 0 0 1px rgba(34,211,238,0.2)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'card',
    },
  },
  {
    id: 'cyber_crimson',
    label: 'Cyber Crimson',
    emoji: '🔻',
    category: 'dark',
    description: 'Red neon pulse. Dangerous future.',
    bgGradient: 'from-[#140205] via-[#240810] to-[#140205]',
    avatarStyle: 'glow',
    previewBg: '#140205',
    previewText: '#fecdd3',
    vars: {
      '--tb-bg':          '#140205',
      '--tb-bg2':         '#240810',
      '--tb-bg3':         '#320f18',
      '--tb-text':        '#ffe4ec',
      '--tb-text2':       '#fb7185',
      '--tb-border':      'rgba(244,63,94,0.4)',
      '--tb-radius':      '14px',
      '--tb-font':        '"Orbitron", "Space Grotesk", sans-serif',
      '--tb-font-display':'"Orbitron", sans-serif',
      '--tb-shadow':      '0 0 40px rgba(244,63,94,0.2), 0 0 0 1px rgba(251,113,133,0.25)',
      '--tb-card-style':  'glass',
      '--tb-link-style':  'pill',
    },
  },

  {
    id: 'azul',
    label: 'Blue',
    emoji: '🔷',
    category: 'gradient',
    description: 'Full-page saturated blue.',
    bgGradient: 'from-blue-600 via-blue-700 to-blue-800',
    avatarStyle: 'ring-accent',
    previewBg: '#2563eb',
    previewText: '#ffffff',
    vars: {
      '--tb-bg': '#2563eb',
      '--tb-bg2': '#1d4ed8',
      '--tb-bg3': '#1e40af',
      '--tb-text': '#ffffff',
      '--tb-text2': 'rgba(219,234,254,0.88)',
      '--tb-border': 'rgba(255,255,255,0.25)',
      '--tb-radius': '14px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 40px rgba(37,99,235,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'amarelo',
    label: 'Yellow',
    emoji: '🟡',
    category: 'gradient',
    description: 'Bright sun yellow fill.',
    bgGradient: 'from-yellow-300 via-yellow-400 to-amber-500',
    avatarStyle: 'shadow',
    previewBg: '#facc15',
    previewText: '#422006',
    vars: {
      '--tb-bg': '#facc15',
      '--tb-bg2': '#eab308',
      '--tb-bg3': '#ca8a04',
      '--tb-text': '#422006',
      '--tb-text2': 'rgba(66,32,6,0.78)',
      '--tb-border': 'rgba(0,0,0,0.18)',
      '--tb-radius': '16px',
      '--tb-font': '"DM Sans", system-ui, sans-serif',
      '--tb-font-display': '"DM Sans", sans-serif',
      '--tb-shadow': '0 10px 32px rgba(202,138,4,0.25)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'dourado_luz',
    label: 'Bright gold',
    emoji: '✨',
    category: 'luxury',
    description: 'Rich amber gold background.',
    bgGradient: 'from-amber-300 via-amber-400 to-amber-600',
    avatarStyle: 'border-gradient',
    previewBg: '#f59e0b',
    previewText: '#422006',
    vars: {
      '--tb-bg': '#f59e0b',
      '--tb-bg2': '#d97706',
      '--tb-bg3': '#b45309',
      '--tb-text': '#422006',
      '--tb-text2': 'rgba(66,32,6,0.8)',
      '--tb-border': 'rgba(120,53,15,0.28)',
      '--tb-radius': '14px',
      '--tb-font': 'Georgia, serif',
      '--tb-font-display': 'Georgia, serif',
      '--tb-shadow': '0 12px 36px rgba(217,119,6,0.3)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'card',
    },
  },
  {
    id: 'roxo',
    label: 'Purple',
    emoji: '🟣',
    category: 'gradient',
    description: 'Vivid purple page.',
    bgGradient: 'from-violet-500 via-purple-600 to-purple-800',
    avatarStyle: 'glow',
    previewBg: '#9333ea',
    previewText: '#faf5ff',
    vars: {
      '--tb-bg': '#9333ea',
      '--tb-bg2': '#7e22ce',
      '--tb-bg3': '#6b21a8',
      '--tb-text': '#faf5ff',
      '--tb-text2': 'rgba(237,233,254,0.9)',
      '--tb-border': 'rgba(255,255,255,0.28)',
      '--tb-radius': '18px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 40px rgba(126,34,206,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'vermelho',
    label: 'Red',
    emoji: '🔴',
    category: 'gradient',
    description: 'Bold red background.',
    bgGradient: 'from-red-400 via-red-500 to-red-600',
    avatarStyle: 'ring-accent',
    previewBg: '#ef4444',
    previewText: '#fff7ed',
    vars: {
      '--tb-bg': '#ef4444',
      '--tb-bg2': '#dc2626',
      '--tb-bg3': '#b91c1c',
      '--tb-text': '#fff7ed',
      '--tb-text2': 'rgba(255,247,237,0.88)',
      '--tb-border': 'rgba(0,0,0,0.15)',
      '--tb-radius': '12px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 36px rgba(220,38,38,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'vinho',
    label: 'Wine',
    emoji: '🍷',
    category: 'gradient',
    description: 'Wine burgundy fill.',
    bgGradient: 'from-rose-700 via-rose-800 to-rose-900',
    avatarStyle: 'glow',
    previewBg: '#9f1239',
    previewText: '#ffe4e6',
    vars: {
      '--tb-bg': '#9f1239',
      '--tb-bg2': '#881337',
      '--tb-bg3': '#6f0f2a',
      '--tb-text': '#ffe4e6',
      '--tb-text2': 'rgba(255,228,230,0.88)',
      '--tb-border': 'rgba(255,255,255,0.22)',
      '--tb-radius': '16px',
      '--tb-font': 'Georgia, serif',
      '--tb-font-display': 'Georgia, serif',
      '--tb-shadow': '0 12px 36px rgba(136,19,55,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'verde_nativo',
    label: 'Green',
    emoji: '🌿',
    category: 'gradient',
    description: 'Fresh green page.',
    bgGradient: 'from-green-500 via-green-600 to-green-800',
    avatarStyle: 'ring-accent',
    previewBg: '#16a34a',
    previewText: '#f0fdf4',
    vars: {
      '--tb-bg': '#16a34a',
      '--tb-bg2': '#15803d',
      '--tb-bg3': '#166534',
      '--tb-text': '#f0fdf4',
      '--tb-text2': 'rgba(220,252,231,0.9)',
      '--tb-border': 'rgba(255,255,255,0.22)',
      '--tb-radius': '14px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 36px rgba(22,163,74,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'lima',
    label: 'Lime',
    emoji: '💚',
    category: 'light',
    description: 'Electric lime green.',
    bgGradient: 'from-lime-200 via-lime-300 to-lime-400',
    avatarStyle: 'shadow',
    previewBg: '#bef264',
    previewText: '#1a2e05',
    vars: {
      '--tb-bg': '#bef264',
      '--tb-bg2': '#a3e635',
      '--tb-bg3': '#84cc16',
      '--tb-text': '#1a2e05',
      '--tb-text2': 'rgba(26,46,5,0.78)',
      '--tb-border': 'rgba(21,128,61,0.28)',
      '--tb-radius': '16px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 10px 32px rgba(132,204,22,0.28)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'prata',
    label: 'Silver',
    emoji: '🪙',
    category: 'gradient',
    description: 'Cyan “metal” shine (colourful, not grey).',
    bgGradient: 'from-cyan-400 via-sky-400 to-sky-600',
    avatarStyle: 'ring-white',
    previewBg: '#22d3ee',
    previewText: '#f0f9ff',
    vars: {
      '--tb-bg': '#22d3ee',
      '--tb-bg2': '#0ea5e9',
      '--tb-bg3': '#0284c7',
      '--tb-text': '#f0f9ff',
      '--tb-text2': 'rgba(224,242,254,0.9)',
      '--tb-border': 'rgba(255,255,255,0.3)',
      '--tb-radius': '12px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 14px 44px rgba(14,165,233,0.4)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'aco_escovado',
    label: 'Brushed steel',
    emoji: '🔩',
    category: 'gradient',
    description: 'Teal steel brush strokes.',
    bgGradient: 'from-cyan-700 via-teal-700 to-cyan-900',
    avatarStyle: 'shadow',
    previewBg: '#0891b2',
    previewText: '#ecfeff',
    vars: {
      '--tb-bg': '#0891b2',
      '--tb-bg2': '#0e7490',
      '--tb-bg3': '#155e75',
      '--tb-text': '#ecfeff',
      '--tb-text2': 'rgba(207,250,254,0.88)',
      '--tb-border': 'rgba(255,255,255,0.22)',
      '--tb-radius': '8px',
      '--tb-font': '"IBM Plex Sans", sans-serif',
      '--tb-font-display': '"IBM Plex Sans", sans-serif',
      '--tb-shadow': '0 14px 40px rgba(8,145,178,0.35)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'card',
    },
  },
  {
    id: 'neon_mix',
    label: 'Neon mix',
    emoji: '🌈',
    category: 'gradient',
    description: 'Rainbow gradient page.',
    bgGradient: 'from-fuchsia-500 via-violet-600 to-cyan-500',
    avatarStyle: 'glow',
    previewBg: '#a855f7',
    previewText: '#ffffff',
    vars: {
      '--tb-bg': '#a855f7',
      '--tb-bg2': '#7c3aed',
      '--tb-bg3': '#6366f1',
      '--tb-text': '#ffffff',
      '--tb-text2': 'rgba(255,255,255,0.9)',
      '--tb-border': 'rgba(255,255,255,0.35)',
      '--tb-radius': '20px',
      '--tb-font': '"Space Grotesk", sans-serif',
      '--tb-font-display': '"Space Grotesk", sans-serif',
      '--tb-shadow': '0 16px 48px rgba(124,58,237,0.4)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'lilas',
    label: 'Lilac',
    emoji: '💜',
    category: 'light',
    description: 'Saturated lilac (not off-white).',
    bgGradient: 'from-violet-200 via-violet-300 to-purple-400',
    avatarStyle: 'shadow',
    previewBg: '#c4b5fd',
    previewText: '#3b0764',
    vars: {
      '--tb-bg': '#c4b5fd',
      '--tb-bg2': '#a78bfa',
      '--tb-bg3': '#8b5cf6',
      '--tb-text': '#3b0764',
      '--tb-text2': 'rgba(59,7,100,0.82)',
      '--tb-border': 'rgba(91,33,182,0.28)',
      '--tb-radius': '18px',
      '--tb-font': '"DM Sans", sans-serif',
      '--tb-font-display': '"DM Sans", sans-serif',
      '--tb-shadow': '0 12px 36px rgba(139,92,246,0.25)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'banana',
    label: 'Banana',
    emoji: '🍌',
    category: 'light',
    description: 'Bright banana yellow.',
    bgGradient: 'from-yellow-200 via-yellow-300 to-yellow-400',
    avatarStyle: 'shadow',
    previewBg: '#fde047',
    previewText: '#422006',
    vars: {
      '--tb-bg': '#fde047',
      '--tb-bg2': '#facc15',
      '--tb-bg3': '#eab308',
      '--tb-text': '#422006',
      '--tb-text2': 'rgba(66,32,6,0.78)',
      '--tb-border': 'rgba(194,65,12,0.22)',
      '--tb-radius': '20px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 32px rgba(234,179,8,0.28)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'abacate',
    label: 'Avocado',
    emoji: '🥑',
    category: 'gradient',
    description: 'Vibrant avocado green.',
    bgGradient: 'from-lime-500 via-lime-600 to-lime-800',
    avatarStyle: 'ring-accent',
    previewBg: '#65a30d',
    previewText: '#ecfccb',
    vars: {
      '--tb-bg': '#65a30d',
      '--tb-bg2': '#4d7c0f',
      '--tb-bg3': '#3f6212',
      '--tb-text': '#ecfccb',
      '--tb-text2': 'rgba(236,252,203,0.92)',
      '--tb-border': 'rgba(0,0,0,0.15)',
      '--tb-radius': '16px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 36px rgba(101,163,13,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'maca',
    label: 'Apple red',
    emoji: '🍎',
    category: 'gradient',
    description: 'Juicy apple red.',
    bgGradient: 'from-rose-400 via-rose-500 to-rose-600',
    avatarStyle: 'glow',
    previewBg: '#f43f5e',
    previewText: '#fff1f2',
    vars: {
      '--tb-bg': '#f43f5e',
      '--tb-bg2': '#e11d48',
      '--tb-bg3': '#be123c',
      '--tb-text': '#fff1f2',
      '--tb-text2': 'rgba(255,241,242,0.9)',
      '--tb-border': 'rgba(0,0,0,0.12)',
      '--tb-radius': '14px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 12px 36px rgba(225,29,72,0.35)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'royal_blue',
    label: 'Royal blue',
    emoji: '💎',
    category: 'gradient',
    description: 'Intense royal blue.',
    bgGradient: 'from-blue-800 via-blue-700 to-blue-600',
    avatarStyle: 'ring-accent',
    previewBg: '#1e40af',
    previewText: '#eff6ff',
    vars: {
      '--tb-bg': '#1e40af',
      '--tb-bg2': '#1d4ed8',
      '--tb-bg3': '#2563eb',
      '--tb-text': '#eff6ff',
      '--tb-text2': 'rgba(219,234,254,0.9)',
      '--tb-border': 'rgba(255,255,255,0.25)',
      '--tb-radius': '14px',
      '--tb-font': 'system-ui, sans-serif',
      '--tb-font-display': 'system-ui, sans-serif',
      '--tb-shadow': '0 14px 44px rgba(29,78,216,0.4)',
      '--tb-card-style': 'glass',
      '--tb-link-style': 'pill',
    },
  },
  {
    id: 'mapa_tesouro',
    label: 'Treasure map',
    emoji: '🗺️',
    category: 'luxury',
    description: 'Golden treasure map tones.',
    bgGradient: 'from-amber-500 via-amber-600 to-amber-800',
    avatarStyle: 'border-gradient',
    previewBg: '#d97706',
    previewText: '#292524',
    vars: {
      '--tb-bg': '#d97706',
      '--tb-bg2': '#b45309',
      '--tb-bg3': '#92400e',
      '--tb-text': '#292524',
      '--tb-text2': 'rgba(41,37,36,0.85)',
      '--tb-border': 'rgba(66,32,6,0.22)',
      '--tb-radius': '8px',
      '--tb-font': 'Georgia, serif',
      '--tb-font-display': 'Georgia, serif',
      '--tb-shadow': '0 12px 32px rgba(180,83,9,0.3)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'line',
    },
  },
  {
    id: 'manchado',
    label: 'Stained paper',
    emoji: '☕',
    category: 'light',
    description: 'Orange & amber stained look.',
    bgGradient: 'from-orange-300 via-orange-400 to-orange-600',
    avatarStyle: 'shadow',
    previewBg: '#fb923c',
    previewText: '#431407',
    vars: {
      '--tb-bg': '#fb923c',
      '--tb-bg2': '#f97316',
      '--tb-bg3': '#ea580c',
      '--tb-text': '#431407',
      '--tb-text2': 'rgba(67,20,7,0.82)',
      '--tb-border': 'rgba(124,45,18,0.28)',
      '--tb-radius': '10px',
      '--tb-font': 'Georgia, serif',
      '--tb-font-display': 'Georgia, serif',
      '--tb-shadow': '0 12px 32px rgba(234,88,12,0.28)',
      '--tb-card-style': 'solid',
      '--tb-link-style': 'card',
    },
  },
];

export const THEME_MAP = Object.fromEntries(THEMES.map(t => [t.id, t]));
export const DEFAULT_THEME = THEMES[0];

// Build inline style string from theme vars + accent color
export function buildThemeStyle(themeId: string, accentColor: string): string {
  const theme = THEME_MAP[themeId] ?? DEFAULT_THEME;
  const vars = Object.entries(theme.vars)
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ');
  return `${vars}; --tb-accent: ${accentColor}; --tb-accent-dim: ${accentColor}22;`;
}

// CSS applied to every mini-site — reads from theme vars
export const SITE_BASE_CSS = `
  .tb-bg        { background: var(--tb-bg); }
  .tb-card      { background: var(--tb-bg2); border: 1px solid var(--tb-border); border-radius: var(--tb-radius); box-shadow: var(--tb-shadow); }
  .tb-card.glass{ backdrop-filter: blur(20px); background: color-mix(in srgb, var(--tb-bg2) 60%, transparent); }
  .tb-text      { color: var(--tb-text); font-family: var(--tb-font); }
  .tb-text2     { color: var(--tb-text2); }
  .tb-accent    { color: var(--tb-accent); }
  .tb-link-pill { background: var(--tb-bg2); border: 1px solid var(--tb-border); border-radius: 999px; padding: 12px 20px; display: flex; align-items: center; gap: 10px; transition: all .2s; }
  .tb-link-pill:hover { border-color: var(--tb-accent); transform: translateY(-1px); box-shadow: 0 4px 16px var(--tb-accent-dim); }
  .tb-link-card { background: var(--tb-bg2); border: 1px solid var(--tb-border); border-radius: var(--tb-radius); padding: 14px 20px; display: flex; align-items: center; gap: 10px; transition: all .2s; }
  .tb-link-card:hover { border-color: var(--tb-accent); }
  .tb-link-line { border-bottom: 1px solid var(--tb-border); padding: 14px 0; display: flex; align-items: center; gap: 10px; transition: all .2s; }
  .tb-link-line:hover { border-color: var(--tb-accent); }
  .tb-link-block{ background: var(--tb-accent); color: white; border-radius: var(--tb-radius); padding: 14px 20px; display: flex; align-items: center; justify-content: center; gap: 10px; font-weight: 700; transition: all .2s; }
  .tb-link-block:hover { opacity: .9; transform: translateY(-1px); }
`;
